server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docmind_db?currentSchema=intelligence
    username: postgres
    password: '{cipher}a84d1abec6c38392076f01671913333598ffef9244861247b6a9e5c0e79f3bf1'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: intelligence
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  ai:
    openai:
      api-key: '{cipher}32d32139300b006b73e9a21612ecc2c9f48b3d911741e22a21919c20e1b1d412f7b2091b07119cbc1aeb0222b298650b19d6ccc47c1f4de524da9766be0d8eeeb804caefad30c3f3d8522e405bbbfe6e'
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7
          max-tokens: 2000
      embedding:
        options:
          model: text-embedding-3-small

  vector-store:
    pgvector:
      schema-name: intelligence
      table-name: document_embeddings
      dimensions: 1536
      distance-type: COSINE_DISTANCE
      initialize-schema: true

docmind:
  messaging:
    queues:
      document-processing: document.processing.queue
      document-processed: document.processed.queue
  ai:
    langchain4j:
      chat-model:
        provider: openai
        model-name: gpt-4o
        temperature: 0.7
        max-tokens: 2000
      rag:
        max-results: 5
        min-score: 0.7

logging:
  level:
    com.docmind.intelligence: DEBUG
    dev.langchain4j: DEBUG
