server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/docmind_db?currentSchema=auth
    username: postgres
    password: '{cipher}a84d1abec6c38392076f01671913333598ffef9244861247b6a9e5c0e79f3bf1'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: auth
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      secret: '{cipher}aae88167684fa4fd51ecb0e5cbf2492ecdd3b37aad205f51d05760112485c97ca790da233aaa64e0f6dcf7e5ffc56237'
      expiration-ms: 86400000        # 24 hours
      refresh-expiration-ms: 604800000  # 7 days

logging:
  level:
    com.docmind.authgateway: DEBUG
    org.springframework.security: DEBUG
